config/routes.rb
Edufyme::Application.routes.draw do

  root to: 'courses#index'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  match 'users/:id' => 'users#dashboard', :as => :user_dashboard
  resources :courses, only: [:index, :show]

  resources :users, only: [] do
    resources :courses, only: [:create, :destroy, :update], controller: "user_courses"
  end

  match 'courses/search/:terms', to: 'courses#search', as: :search, via: :get

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.featured
    if request.xhr?
      @schools = @courses.map { |course| course.school.name }
      render :json => [@courses, @schools]
    end
  end

  def show
    @course = Course.find(params[:id])
    respond_to do |format|
      format.json {render :json => [@course, School.find(@course.school_id)]}
    end
  end

  def search
    @courses = Course.search_for(params["terms"])
    render json: @courses
  end

end

app/views/courses/index.html.erb
<% if user_signed_in? %>
  <div id="current-user-id" display="hidden" data-user-id=<%= current_user.id %>>
  </div>
  <div id="current-user-added-classes" display="hidden" data-added-course-ids="<%= current_user.courses.map {|course| course.id} %>">
  </div>
  <% favorited_array = [] %>
  <% course_user = CourseUser.find_all_by_user_id(current_user.id) %>
  <% course_user.each {|cu| favorited_array << cu.course_id if cu.favorited == true} %>
  <div id="current-user-favorited-classes" display="hidden" data-favorited-course-ids="<%= favorited_array %>">
  </div>
  <% completed_array = [] %>
  <% course_user.each {|cu| completed_array << cu.course_id if cu.completed == true} %>
  <div id="current-user-completed-classes" display="hidden" data-completed-course-ids="<%= completed_array %>">
  </div>
<% end %>
<%= render "shared/top_navbar" %>
<div class="container">
  <div class="login-signup-errors">
    <%= @login_signup_errors %>
  </div>
  <div class="mobile-menu">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Dashboard", user_dashboard_path(current_user) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><a href="#loginmodal" class="flatbtn loginmodaltrigger">Log In</a></li>
        <li><a href="#signupmodal" class="flatbtn signupmodaltrigger">Sign Up</a></li>
      <% end %>
    </ul>
  </div>
  <div class="buffer">
    <div class="featured-courses-title">
      <h2>The Best Way to Keep Track of Your Online Learning</h2>
    </div>
    <div id="featured-title">
      <h3>Featured Courses</h3>
    </div>
  </div>
  <div class="courses-container">
    <% @courses.map do |course| %>
    <div class="course" data-course-id=<%= course.id %>>
      <div class="course-image">
        <img src=<%=course.course_img_url%> alt="Course Image">
        <div class="course-description">
          <%= link_to "#{course.short_title}", course.course_url %>
          <p><%= School.short_school_name(course.school.name) %></p>
          <div class="course-date">
            <span class="date-display">
              <% if course.start_date.nil? %>
                Start Date: Self-Paced
              <% else %>
                Start Date: <%=course.start_date%>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    </div>
    <%end%>
  </div>

  <div class="overlay">
  </div>
  <div class="modal">
    <div class="overlay-course-main">
      <a href="" target="_blank"><h4 class="overlay-course-title"></h4></a>
    </div>
    <div class="overlay-image-and-buttons">
      <img class="course-image" src="" alt="Course Image">
      <div class="overlay-course-sidebar">
        <button class="overlay-remove-course">Remove Course</button>
        <button class="overlay-add-course">Add Course</button>
        <button class="favorite-course" disabled="disabled">Favorite Course</button>
        <button class="unfavorite-course">Unfavorite Course</button>
        <button class="complete-course" disabled="disabled">Complete Course</button>
        <button class="uncomplete-course">Uncomplete Course</button>
        <div id="school">
          <img src="/images/default-school.jpg">
        </div>
        <div class="teachers">
          <h4>Instructor(s)</h4>
          <p></p>
        </div>
      </div>
    </div>
    <h4>Course Description</h4>
    <iframe seamless class="overlay-course-description"></iframe>
  </div>
</div>

<div id="loginmodal" style="display:none;">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <h1>User Login</h1>
  <%= form_for(:user, :url => session_path(:user), html: {id: "loginform"}) do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "txtfield" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "txtfield" %>
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %><br /><br />
    <%= f.submit 'Sign in' %><br /><br />
    <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>
</div>

<div id="signupmodal" style="display:none;">
  <p class="notice"></p>
  <h1>Sign Up</h1>
<%= form_for(:user, :url => registration_path(:user), html: {id: "signupform"}) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email, class: "txtfield" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "txtfield" %>
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, class: "txtfield" %>
  <%= f.label :remember_me %>
  <%= f.check_box :remember_me %><br /><br />
  <%= f.submit 'Sign Up' %><br /><br />
<% end %>
</div>

<div id="load-ajax"><img src="images/ajax-loader.gif"></div>

<div class='hidden'>
  <div class="course-template" data-course-id="">
      <div class="course-image">
        <img src="" alt="Course Image">
        <div class="course-description">
          <a href=""></a>
          <p></p>
          <div class="course-date">
            <span class="date-display"></span>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/courses/search_results.html.erb
<% @courses.each do |course| %>
<%= link_to(course.title, course.course.url) %>
<% end %>